apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm/templates
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: audit-db
  name: audit-db
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.kompose.service: audit-db
status:
  loadBalancer: {}
